- app/build.gradle
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
If there is current user. Go to main
> Auto Login

- app/src/main/java/com/example/test/myreceipts/BLL/GroupCollectionService.java
- app/src/main/java/com/example/test/myreceipts/BLL/ReceiptService.java
- app/src/main/java/com/example/test/myreceipts/ButtonAdapter.java
- app/src/main/java/com/example/test/myreceipts/MainActivity.java
added a service and a way of getting cities from firebase
> groupcollectionservice added

- app/src/main/java/com/example/test/myreceipts/BLL/Callback.java
- app/src/main/java/com/example/test/myreceipts/BLL/UserService.java
- app/src/main/java/com/example/test/myreceipts/Entity/User.java
- app/src/main/java/com/example/test/myreceipts/ProfileActivity.java
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
- app/src/main/res/layout/activity_profile.xml
Get a single user moved to service
Update user moved to service and fails handles
Creates an user in database when new account is created
> A lot to do with an User

- app/src/main/java/com/example/test/myreceipts/ImageActivity.java
- app/src/main/res/layout/image_activity.xml
Minor changes, removed the location
> Minor changes, removed the location

- app/src/main/java/com/example/test/myreceipts/BLL/UserService.java
- app/src/main/java/com/example/test/myreceipts/Entity/User.java
- app/src/main/java/com/example/test/myreceipts/ProfileActivity.java
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
- app/src/main/res/layout/activity_profile.xml
- app/src/main/res/layout/activity_sign_in.xml
Refactored for that.
Also is it possible to reset password
>  The firebase method newuser works as update aswell

- app/src/main/java/com/example/test/myreceipts/BLL/UserService.java
- app/src/main/java/com/example/test/myreceipts/ProfileActivity.java
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
Small error handling with listeners.
> Creates an empty folder 'Favorites' on a new user

- app/src/main/java/com/example/test/myreceipts/ProfileActivity.java
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
> Smaill bugfix

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/test/myreceipts/CustomMenu.java
- app/src/main/java/com/example/test/myreceipts/ImageActivity.java
- app/src/main/java/com/example/test/myreceipts/ImageGroup.java
- app/src/main/java/com/example/test/myreceipts/MainActivity.java
- app/src/main/java/com/example/test/myreceipts/ProfileActivity.java
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
- app/src/main/res/layout/activity_main.xml
- app/src/main/res/menu/menu_top.xml
- app/src/main/res/values/colors.xml
Menu for all activities. extends the custommenu class.
Back button in the menu.
Changed design color to orange
Icon instead of button on the mainActivity
> Menu & Design

- app/src/main/java/com/example/test/myreceipts/BLL/ReceiptService.java
- app/src/main/java/com/example/test/myreceipts/DAL/DAO.java
- app/src/main/java/com/example/test/myreceipts/ImageGroup.java
- app/src/main/java/com/example/test/myreceipts/MainActivity.java
Shows categories.
TODO: move to DAO
> show categories

- app/src/main/java/com/example/test/myreceipts/CustomMenu.java
- app/src/main/java/com/example/test/myreceipts/ImageActivity.java
- app/src/main/java/com/example/test/myreceipts/ImageGroup.java
- app/src/main/java/com/example/test/myreceipts/MainActivity.java
- app/src/main/java/com/example/test/myreceipts/ProfileActivity.java
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
backbutton removed from main
build in back button takes you to start screen on phone
removed profile menu item in profile view
> Small changes with the menu

- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
Override build in back button in login view
>  Override build in back button in login view

- app/src/main/java/com/example/test/myreceipts/CustomMenu.java
- app/src/main/res/menu/menu_top.xml
Menu item for create category on all activities.
Creating an category will refresh page to make sure its updated correctly.
> MenuItem Create Category

- app/src/main/java/com/example/test/myreceipts/ImageActivity.java
- app/src/main/java/com/example/test/myreceipts/MainActivity.java
- app/src/main/res/layout/activity_main.xml
UI waiting progressbar made so the use can see something is going on.
> UI for user

- app/src/main/java/com/example/test/myreceipts/CustomMenu.java
saves the new category as lower case
> lowercase cat

- app/src/main/java/com/example/test/myreceipts/BLL/UserService.java
- app/src/main/java/com/example/test/myreceipts/SignInActivity.java
added auto create of unassigned folder
> added unassigned

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/example/test/myreceipts/BLL/ImageHandler.java
- app/src/main/java/com/example/test/myreceipts/CategoryActivity.java
- app/src/main/java/com/example/test/myreceipts/DAL/DAO.java
- app/src/main/java/com/example/test/myreceipts/Entity/Receipt.java
- app/src/main/java/com/example/test/myreceipts/ProfileActivity.java
- app/src/main/java/com/example/test/myreceipts/ReceiptActivity.java
- app/src/main/res/layout/activity_receipt.xml
- app/src/main/res/layout/category_activity.xml
- app/src/main/res/layout/cell_extended.xml
A list with the repeipts from the selected category
Not all functional 
Needs to auto set the list, and not on the button
OPens a new with view from the selected position 
Created a new view, with a single row. sets this row with for each new object
>  Something with the list 

- app/src/main/java/com/example/test/myreceipts/BLL/CategoryService.java
major refactoring and javadoc for the catagory service class
> CategoryService refactoring

- app/src/main/java/com/example/test/myreceipts/ImageActivity.java
refactored the ImageActivity class and added javasoc
> ImageActivity refactor

- app/src/main/java/com/example/test/myreceipts/BLL/ImageHandler.java
- app/src/main/java/com/example/test/myreceipts/CategoryActivity.java
- app/src/main/java/com/example/test/myreceipts/ListAdapter.java
- app/src/main/res/layout/category_activity.xml
The list auto update some (the file names) and some pic.
Updates the rest by scroll.
Can crach, if scrolling, when the list isn't updated
> List view show the files for the categories

- app/src/main/java/com/example/test/myreceipts/BLL/CategoryService.java
- app/src/main/java/com/example/test/myreceipts/DAL/DAO.java
- app/src/main/java/com/example/test/myreceipts/ImageActivity.java
> javadoc refactor

- app/src/main/java/com/example/test/myreceipts/CategoryActivity.java
- app/src/main/java/com/example/test/myreceipts/ListAdapter.java
- app/src/main/java/com/example/test/myreceipts/ReceiptActivity.java
Thread for firebase handling
Auto update list.
Send entity further.
Show the image of selected receipt in the next view
> The list show the files correctly
